# my-backendconfig.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 20
    port: 8
    type: HTTP
    requestPath: /actuator/health/readiness
  timeoutSec: 41
  connectionDraining:
    drainingTimeoutSec: 60